"""empty message

Revision ID: c58d76e7fe1f
Revises: 
Create Date: 2020-07-16 21:07:42.005428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58d76e7fe1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('is_employee', sa.Boolean(), nullable=True),
    sa.Column('is_employer', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('social_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=64000), nullable=True),
    sa.Column('owner_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('account')
    # ### end Alembic commands ###
